---
title: "data cleaning"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-12-02"
---


```{r, message=F, warning=F}
rm(list=ls())
set.seed(123)
library(tidyverse)
```


## load and preprocess brainspan data

```{r, message=F, warning=F, eval=T}
load("newGenexp.RData")
rownames(genexp) <- genexp[,1]
genexp <- genexp[,-1]
genexp <- t(genexp)
genexp <- as.data.frame(genexp) 
missed_genes=c("SETD1A","FAM178A","OR4P4","PCLO")  # these genes are missed in the final risk gene list, but supposed to be included, sum(colnames(genexp) %in% missed_genes)=0, two genes "SETD1A", and "PCLO" not in genexp  


#determine brain-expressed genes

load("brain_expression.rda") # brain_expression has 4 missed genes sum(brain_expression$Gene %in% missed_genes)
brain_genes <- brain_expression$Gene[brain_expression$Brain_expressed != 'No']   ## "OR4P4" is not in brain_genes 
idx <- which(colnames(genexp) %in% brain_genes)
genexp <- genexp[,idx] # 1340 x 14370  # only FAM178A of 4 missed genes is in genexp now:  missed_genes %in% colnames(genexp)


#translate into synonyms
source("cleaning.R")

vec <- symbol_synonyms(colnames(genexp), verbose = T)
unknown_genes_idx <- which(is.na(vec))
vec <- vec[-unknown_genes_idx]
genexp <- genexp[-unknown_genes_idx] # 1340 x 14297
colnames(genexp) <- vec   ##  4 missed genes are missed now 


genexp <- average_same_columns(genexp) # 1340 x 14237


load("region_subregion.rda")
region_subregion <- region_subregion 
vec <- rownames(genexp)
# extract regions from colnames 
subregion <- unlist(strsplit(vec,"\\."))[seq(2, length(vec)*4, 4)] 
idx <- which(subregion %in% region_subregion$subregion)
genexp <- genexp[idx,] # 1294 X 14237

```




## read into SCHEMA p values 

```{r,  message=F, warning=F, results=F, eval=T}
multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}

####
# load SCZ gene 
SCHEMA_gene_results=multiplesheets("41586_2022_4556_MOESM3_ESM.xlsx")
scz1=data.frame(Gene=SCHEMA_gene_results$`Table S5 - Gene Results`$`Gene Symbol`, pval.meta=SCHEMA_gene_results$`Table S5 - Gene Results`$`P meta`, qval.meta=SCHEMA_gene_results$`Table S5 - Gene Results`$`Q meta`, dn_PTV=SCHEMA_gene_results$`Table S5 - Gene Results`$`De novo PTV`) 
scz1$dn_PTV[is.na(scz1$dn_PTV)]=0   # fill missing PTV with 0 
scz1=scz1%>% drop_na()  # remove NA's  ######## this is important 

scz2=scz1[-c(9934,  9935,  9936, 13100),]   #  remove duplicates which(duplicated(scz1$Gene)==T)

```




## find relevant spatio-temporal BrainSpan data 

```{r, message=F, warning=F, eval=T}
#match the order in both datasets ########## check this part 
idx <- which(colnames(genexp) %in% scz2$Gene)
genexp <- genexp[,idx] # 1294 x 13964
idx <- which(scz2$Gene %in% colnames(genexp))
scz3=scz2[idx,] # 4 risk genes not in gene expression data:  scz2$Gene[which(!scz2$Gene[1:32]%in%colnames(genexp))]


source("misc.R") # load functions 

idx <- matching(scz3$Gene, colnames(genexp))
genexp <- genexp[,idx]  # 1294 x 12879 




dat_list <- extractor(genexp) # 212 partitions # extractor is a function in cleaning.R 
dat_list <- lapply(dat_list, as.matrix, drop = F)

# remove partitions too small
idx <- which(sapply(dat_list, function(x){ifelse(nrow(x) >= 5, T, F)}))
dat_list <- dat_list[idx] # 125 partitions
dat_list <- lapply(dat_list, scale, scale = F)  # 125 partitions 



```







## run screening step 





```{r, message=F, warning=F, eval=T}

p_thres_screening <- 0.01 
p_primary <- 0.1
num_genes <- 3100 # constraint genes with pLI>0.9 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9805802/




selected_idx <- grep("PFC\\.[3-5]", names(dat_list)) # [3-5] should be early PC in Liu et.al 2015 (10-19 post conception week) 
dat_pfc35 <- do.call(rbind, dat_list[selected_idx])  




source("screen.R") # load functions downloaded in local folder
screening_res <- screen(dat_pfc35, pv = scz3$pval.meta, p_thres = p_thres_screening, 
                                             num_genes = num_genes)


# reorder which genes are primary and which are secondary
all_idx <- sort(unique(c(screening_res$primary, screening_res$secondary)))
screening_res$primary <- all_idx[which(scz3$pval.meta[all_idx] < p_primary)]
screening_res$secondary <- setdiff(all_idx, screening_res$primary)

# apply the new gene list
for(i in 1:length(dat_list)){
  dat_list[[i]] <- dat_list[[i]][,c(screening_res$primary, screening_res$secondary)]
}

 scz=scz3[c(screening_res$primary, screening_res$secondary),]   # 3100 x 4 
                
 
 ############## redefine dat_pfc35
selected_idx <- grep("PFC\\.[3-5]", names(dat_list))
dat_pfc35 <- do.call(rbind, dat_list[selected_idx]) # 107 x 3100
dat_pfc35 <- scale(dat_pfc35, scale = F)
stopifnot(sum(colnames(dat_pfc35)%in%colnames(genexp))==num_genes)
```



## Choosing tuning parameters 




```{r, message=F, warning=F, eval=T, results=F}

# estimate graphical model on PFC35 using cross-validated lasso for neighborhood selection
source("graphicalModel.R")
res <- graphicalModel_range(dat_pfc35, 1:length(screening_res$primary), 
                                                  lambda_min = 0.01, lambda_max = 0.35, 
                                                  lambda_length = 30, verbose = T)

 
```



```{r, message=F, warning=F, eval=T}
source("graph_functions.R")
 
scale_vec_pfc35 <- sapply(res, function(x){compute_scale_free(as.matrix(x$adj_mat))})

 idx <- which.max(scale_vec_pfc35) # choose tuning parameter lambda maximizing R^2 

 adj_pfc35 <- as.matrix(res[[idx]]$adj_mat)



stopifnot(all(dim(adj_pfc35) == nrow(scz)))
```


## Run HMRF


```{r, message=F, warning=F, eval=T}
fdr_cutoff <- 0.05
# run the HMRF
set.seed(10)
seedindex <- rep(0, ncol(adj_pfc35))
seedindex[which(scz$dn_PTV >= 1)] <- 1

set.seed(10)

scz$pval.meta[which(scz$pval.meta==1)]=1-10^{-7}; # enforce 1 pvalues to be slightly less than 1  

source("hmrf.R")
hmrf_pfc35 <- hmrf(scz$pval.meta, adj_pfc35, seedindex, pthres = 0.1)  # pval must not be 0 or 1's, i.e between 0 and 1


report_pfc35 <- report_results(scz$Gene, 1-hmrf_pfc35$post, scz$pval.meta, hmrf_pfc35$Iupdate)
genes_pfc35 <- sort(as.character(report_pfc35$Gene[which(report_pfc35$FDR <= fdr_cutoff)]))
genes_pfc35

adj_pfc35 <- Matrix::Matrix(adj_pfc35, sparse = T)


report_pfc35_sort=report_pfc35[order(report_pfc35$FDR),]
report_pfc35_sort[report_pfc35_sort$FDR<=fdr_cutoff,]



```


